# Generated by Django 2.2.8 on 2020-01-09 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('location', models.TextField(blank=True, max_length=100)),
                ('list_type', models.IntegerField(choices=[(1, 'Cooled'), (2, 'Shopping')])),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'lists',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activeAs1', to='our_groceries.List')),
                ('list2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activeAs2', to='our_groceries.List')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'userprofiles',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.IntegerField(choices=[(1, 'Read'), (2, 'Approval_req'), (3, 'Modify'), (4, 'Co-owner')])),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='our_groceries.List')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('checked', models.BooleanField(default=False)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('amount', models.PositiveIntegerField(null=True)),
                ('accepted', models.BooleanField(default=True)),
                ('expires', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='our_groceries.List')),
            ],
            options={
                'verbose_name_plural': 'items',
            },
        ),
    ]
